# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debugWindow.ui'
#
# Created: Thu Mar 24 22:24:29 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 300)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setWindowTitle("Debug")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sanvenirtin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 261, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.loveText = QtGui.QLabel(self.gridLayoutWidget)
        self.loveText.setObjectName("loveText")
        self.gridLayout.addWidget(self.loveText, 2, 1, 1, 1)
        self.fearText = QtGui.QLabel(self.gridLayoutWidget)
        self.fearText.setObjectName("fearText")
        self.gridLayout.addWidget(self.fearText, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.hateText = QtGui.QLabel(self.gridLayoutWidget)
        self.hateText.setObjectName("hateText")
        self.gridLayout.addWidget(self.hateText, 4, 1, 1, 1)
        self.friendshipText = QtGui.QLabel(self.gridLayoutWidget)
        self.friendshipText.setObjectName("friendshipText")
        self.gridLayout.addWidget(self.friendshipText, 1, 1, 1, 1)
        self.label2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 1, 0, 1, 1)
        self.tiredText = QtGui.QLabel(self.gridLayoutWidget)
        self.tiredText.setObjectName("tiredText")
        self.gridLayout.addWidget(self.tiredText, 5, 1, 1, 1)
        self.familiarText = QtGui.QLabel(self.gridLayoutWidget)
        self.familiarText.setObjectName("familiarText")
        self.gridLayout.addWidget(self.familiarText, 0, 1, 1, 1)
        self.label2_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label2_2.setObjectName("label2_2")
        self.gridLayout.addWidget(self.label2_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.happyText = QtGui.QLabel(self.gridLayoutWidget)
        self.happyText.setObjectName("happyText")
        self.gridLayout.addWidget(self.happyText, 0, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.angryText = QtGui.QLabel(self.gridLayoutWidget)
        self.angryText.setObjectName("angryText")
        self.gridLayout.addWidget(self.angryText, 1, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 2, 1, 1)
        self.sorrowText = QtGui.QLabel(self.gridLayoutWidget)
        self.sorrowText.setObjectName("sorrowText")
        self.gridLayout.addWidget(self.sorrowText, 2, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 2, 1, 1)
        self.horrorText = QtGui.QLabel(self.gridLayoutWidget)
        self.horrorText.setObjectName("horrorText")
        self.gridLayout.addWidget(self.horrorText, 3, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 2, 1, 1)
        self.surprisedText = QtGui.QLabel(self.gridLayoutWidget)
        self.surprisedText.setObjectName("surprisedText")
        self.gridLayout.addWidget(self.surprisedText, 4, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 5, 2, 1, 1)
        self.shynessText = QtGui.QLabel(self.gridLayoutWidget)
        self.shynessText.setObjectName("shynessText")
        self.gridLayout.addWidget(self.shynessText, 5, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "快乐", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "疲劳", None, QtGui.QApplication.UnicodeUTF8))
        self.loveText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.fearText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "仇恨", None, QtGui.QApplication.UnicodeUTF8))
        self.hateText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.friendshipText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "友好", None, QtGui.QApplication.UnicodeUTF8))
        self.tiredText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.familiarText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label2_2.setText(QtGui.QApplication.translate("Dialog", "熟悉度", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "恐惧", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "爱情", None, QtGui.QApplication.UnicodeUTF8))
        self.happyText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "生气", None, QtGui.QApplication.UnicodeUTF8))
        self.angryText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "伤心", None, QtGui.QApplication.UnicodeUTF8))
        self.sorrowText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "害怕", None, QtGui.QApplication.UnicodeUTF8))
        self.horrorText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "惊讶", None, QtGui.QApplication.UnicodeUTF8))
        self.surprisedText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "害羞", None, QtGui.QApplication.UnicodeUTF8))
        self.shynessText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

